use crate::{
    Result,
    model::{Metadata, Note, validate_meta},
};
use std::{io::BufRead, path::Path};

pub const START: &str = "<!-- inbox:note ";
pub const END: &str = "<!-- inbox:end ";

pub fn encode(note: &Note) -> Result<String> {
    validate_meta(&note.meta)?;
    // Escape HTML-sensitive characters inside the JSON comment. JSON decoding
    // restores them; a tag containing --> cannot close the metadata comment.
    let metadata = serde_json::to_string(&note.meta)?
        .replace('<', "\\u003c")
        .replace('>', "\\u003e")
        .replace('&', "\\u0026");
    let mut out = format!("{START}{metadata} -->\n");
    for (i, line) in note.content.split('\n').enumerate() {
        if i == 0 {
            out.push_str(&format!("- {} {line}\n", &note.meta.created[11..19]));
        } else {
            out.push_str("  ");
            out.push_str(line);
            out.push('\n');
        }
    }
    out.push_str(&format!("{END}{} -->\n\n", note.meta.id));
    Ok(out)
}

/// Streams complete records. Root-level delimiters cannot be generated by a
/// body line: first lines have a list prefix; every continuation is indented.
pub fn scan(
    mut reader: impl BufRead,
    path: &Path,
    mut visit: impl FnMut(Note) -> Result<()>,
) -> Result<()> {
    let mut pending: Option<Note> = None;
    let mut body_lines = 0;
    let mut saw_header = false;
    let mut last_line = 0;
    let date = path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or("无效的日期文件名")?;
    let header = format!("# {date}");
    let fail = |line: usize, message: &str| -> Box<dyn std::error::Error> {
        format!(
            "{}:{line}: {message}；文件未被修改，请保留备份后修复",
            path.display()
        )
        .into()
    };
    let mut buffer = String::new();
    loop {
        buffer.clear();
        let line_number = last_line + 1;
        if reader
            .read_line(&mut buffer)
            .map_err(|e| fail(line_number, &e.to_string()))?
            == 0
        {
            break;
        }
        last_line = line_number;
        let terminated = buffer.ends_with('\n');
        let line = buffer.strip_suffix('\n').unwrap_or(&buffer);
        let line = line.strip_suffix('\r').unwrap_or(line);
        if !saw_header {
            if line != header {
                return Err(fail(line_number, "缺少或不匹配的日期标题"));
            }
            saw_header = true;
            continue;
        }
        if let Some(note) = pending.as_mut() {
            if line.strip_prefix(END).and_then(|s| s.strip_suffix(" -->"))
                == Some(note.meta.id.as_str())
            {
                if !terminated {
                    return Err(fail(line_number, "结束标记缺少换行，可能是中断写入"));
                }
                if body_lines == 0 || note.content.trim().is_empty() {
                    return Err(fail(line_number, "记录内容为空"));
                }
                visit(pending.take().unwrap())?;
                body_lines = 0;
            } else if body_lines == 0 {
                let prefix = format!("- {} ", &note.meta.created[11..19]);
                let body = line
                    .strip_prefix(&prefix)
                    .ok_or_else(|| fail(line_number, "列表首行格式不正确"))?;
                note.content.push_str(body);
                body_lines += 1;
            } else if let Some(body) = line.strip_prefix("  ") {
                note.content.push('\n');
                note.content.push_str(body);
                body_lines += 1;
            } else if line.is_empty() {
                // Editors commonly trim whitespace from empty continuation lines.
                note.content.push('\n');
                body_lines += 1;
            } else {
                return Err(fail(
                    line_number,
                    "条目缺少结束标记，或正文续行未缩进两个空格",
                ));
            }
        } else if line.is_empty() {
            continue;
        } else if let Some(json) = line
            .strip_prefix(START)
            .and_then(|s| s.strip_suffix(" -->"))
        {
            let meta: Metadata = serde_json::from_str(json)
                .map_err(|e| fail(line_number, &format!("元数据无效：{e}")))?;
            let timestamp = validate_meta(&meta).map_err(|e| fail(line_number, &e.to_string()))?;
            if &meta.created[..10] != date {
                return Err(fail(line_number, "创建日期与文件名不一致"));
            }
            pending = Some(Note {
                meta,
                timestamp,
                content: String::new(),
            });
        } else {
            return Err(fail(line_number, "无法识别的内容或元数据"));
        }
    }
    if !saw_header {
        return Err(fail(1, "空的日期文件"));
    }
    if pending.is_some() {
        return Err(fail(last_line, "文件尾部存在未完成的记录"));
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::io::Cursor;

    fn sample() -> Note {
        Note::new(
            "中文 🦀\n\n- 嵌套列表\n```rust\nfn main() {}\n```\n<!-- inbox:end 假标记 -->\n".into(),
            vec!["产品".into(), "a-->b".into(), "引号\"反斜\\线".into()],
            &"2026-09-29T09:42:18+08:00[Asia/Shanghai]".parse().unwrap(),
        )
        .unwrap()
    }

    #[test]
    fn markdown_round_trip_preserves_multiline_content_and_tags() {
        let note = sample();
        let encoded = format!("# 2026-09-29\n\n{}", encode(&note).unwrap());
        assert!(!encoded.contains("a-->b"));
        let mut found = Vec::new();
        scan(Cursor::new(encoded), Path::new("2026-09-29.md"), |n| {
            found.push(n);
            Ok(())
        })
        .unwrap();
        assert_eq!(found.len(), 1);
        assert_eq!(found[0].content, note.content);
        assert_eq!(found[0].meta.tags, note.meta.tags);
        assert_eq!(found[0].meta.id, note.meta.id);
    }

    #[test]
    fn truncated_record_is_not_silently_accepted() {
        let note = sample();
        let encoded = format!("# 2026-09-29\n\n{}", encode(&note).unwrap());
        let cutoff = encoded.rfind(END).unwrap();
        let mut count = 0;
        let err = scan(
            Cursor::new(&encoded[..cutoff]),
            Path::new("2026-09-29.md"),
            |_| {
                count += 1;
                Ok(())
            },
        )
        .unwrap_err();
        assert!(err.to_string().contains("未完成"));
        assert_eq!(count, 0);
    }
}
